// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosllm/inference/gpunode.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Gpunode struct {
	GpuModel string `protobuf:"bytes,1,opt,name=gpuModel,proto3" json:"gpuModel,omitempty"`
	Memory   uint64 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Cores    uint64 `protobuf:"varint,3,opt,name=cores,proto3" json:"cores,omitempty"`
}

func (m *Gpunode) Reset()         { *m = Gpunode{} }
func (m *Gpunode) String() string { return proto.CompactTextString(m) }
func (*Gpunode) ProtoMessage()    {}
func (*Gpunode) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b79fde55ba6c2c2, []int{0}
}
func (m *Gpunode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Gpunode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Gpunode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Gpunode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gpunode.Merge(m, src)
}
func (m *Gpunode) XXX_Size() int {
	return m.Size()
}
func (m *Gpunode) XXX_DiscardUnknown() {
	xxx_messageInfo_Gpunode.DiscardUnknown(m)
}

var xxx_messageInfo_Gpunode proto.InternalMessageInfo

func (m *Gpunode) GetGpuModel() string {
	if m != nil {
		return m.GpuModel
	}
	return ""
}

func (m *Gpunode) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Gpunode) GetCores() uint64 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func init() {
	proto.RegisterType((*Gpunode)(nil), "cosmosllm.inference.Gpunode")
}

func init() { proto.RegisterFile("cosmosllm/inference/gpunode.proto", fileDescriptor_1b79fde55ba6c2c2) }

var fileDescriptor_1b79fde55ba6c2c2 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xce, 0xc9, 0xc9, 0xd5, 0xcf, 0xcc, 0x4b, 0x4b, 0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0xd5,
	0x4f, 0x2f, 0x28, 0xcd, 0xcb, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x86,
	0x2b, 0xd1, 0x83, 0x2b, 0x51, 0x0a, 0xe6, 0x62, 0x77, 0x87, 0xa8, 0x12, 0x92, 0xe2, 0xe2, 0x48,
	0x2f, 0x28, 0xf5, 0xcd, 0x4f, 0x49, 0xcd, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x85, 0xc4, 0xb8, 0xd8, 0x72, 0x53, 0x73, 0xf3, 0x8b, 0x2a, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58,
	0x82, 0xa0, 0x3c, 0x21, 0x11, 0x2e, 0xd6, 0xe4, 0xfc, 0xa2, 0xd4, 0x62, 0x09, 0x66, 0xb0, 0x30,
	0x84, 0xe3, 0x64, 0x76, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31,
	0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x32, 0x10,
	0x37, 0xe8, 0x82, 0xdc, 0x59, 0x81, 0xe4, 0xd2, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0xb0,
	0x43, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xc3, 0x7c, 0x42, 0xcd, 0x00, 0x00, 0x00,
}

func (m *Gpunode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Gpunode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Gpunode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cores != 0 {
		i = encodeVarintGpunode(dAtA, i, uint64(m.Cores))
		i--
		dAtA[i] = 0x18
	}
	if m.Memory != 0 {
		i = encodeVarintGpunode(dAtA, i, uint64(m.Memory))
		i--
		dAtA[i] = 0x10
	}
	if len(m.GpuModel) > 0 {
		i -= len(m.GpuModel)
		copy(dAtA[i:], m.GpuModel)
		i = encodeVarintGpunode(dAtA, i, uint64(len(m.GpuModel)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGpunode(dAtA []byte, offset int, v uint64) int {
	offset -= sovGpunode(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Gpunode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GpuModel)
	if l > 0 {
		n += 1 + l + sovGpunode(uint64(l))
	}
	if m.Memory != 0 {
		n += 1 + sovGpunode(uint64(m.Memory))
	}
	if m.Cores != 0 {
		n += 1 + sovGpunode(uint64(m.Cores))
	}
	return n
}

func sovGpunode(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGpunode(x uint64) (n int) {
	return sovGpunode(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Gpunode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGpunode
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Gpunode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Gpunode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GpuModel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpunode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGpunode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGpunode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GpuModel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			m.Memory = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpunode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Memory |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cores", wireType)
			}
			m.Cores = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpunode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cores |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGpunode(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGpunode
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGpunode(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGpunode
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGpunode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGpunode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGpunode
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGpunode
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGpunode
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGpunode        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGpunode          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGpunode = fmt.Errorf("proto: unexpected end of group")
)
