// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosllm/inference/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetInferenceRunRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetInferenceRunRequest) Reset()         { *m = QueryGetInferenceRunRequest{} }
func (m *QueryGetInferenceRunRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetInferenceRunRequest) ProtoMessage()    {}
func (*QueryGetInferenceRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{2}
}
func (m *QueryGetInferenceRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInferenceRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInferenceRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInferenceRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInferenceRunRequest.Merge(m, src)
}
func (m *QueryGetInferenceRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInferenceRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInferenceRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInferenceRunRequest proto.InternalMessageInfo

func (m *QueryGetInferenceRunRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetInferenceRunResponse struct {
	Inference *Inferencerun `protobuf:"bytes,1,opt,name=inference,proto3" json:"inference,omitempty"`
}

func (m *QueryGetInferenceRunResponse) Reset()         { *m = QueryGetInferenceRunResponse{} }
func (m *QueryGetInferenceRunResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetInferenceRunResponse) ProtoMessage()    {}
func (*QueryGetInferenceRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{3}
}
func (m *QueryGetInferenceRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInferenceRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInferenceRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInferenceRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInferenceRunResponse.Merge(m, src)
}
func (m *QueryGetInferenceRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInferenceRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInferenceRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInferenceRunResponse proto.InternalMessageInfo

func (m *QueryGetInferenceRunResponse) GetInference() *Inferencerun {
	if m != nil {
		return m.Inference
	}
	return nil
}

type QueryGetPoolSizeRequest struct {
}

func (m *QueryGetPoolSizeRequest) Reset()         { *m = QueryGetPoolSizeRequest{} }
func (m *QueryGetPoolSizeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPoolSizeRequest) ProtoMessage()    {}
func (*QueryGetPoolSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{4}
}
func (m *QueryGetPoolSizeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPoolSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPoolSizeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPoolSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPoolSizeRequest.Merge(m, src)
}
func (m *QueryGetPoolSizeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPoolSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPoolSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPoolSizeRequest proto.InternalMessageInfo

type QueryGetPoolSizeResponse struct {
	Size_ uint64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (m *QueryGetPoolSizeResponse) Reset()         { *m = QueryGetPoolSizeResponse{} }
func (m *QueryGetPoolSizeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPoolSizeResponse) ProtoMessage()    {}
func (*QueryGetPoolSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{5}
}
func (m *QueryGetPoolSizeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPoolSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPoolSizeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPoolSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPoolSizeResponse.Merge(m, src)
}
func (m *QueryGetPoolSizeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPoolSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPoolSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPoolSizeResponse proto.InternalMessageInfo

func (m *QueryGetPoolSizeResponse) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

type QueryGetUnansweredInferenceRunRequest struct {
	ModelId uint64 `protobuf:"varint,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
}

func (m *QueryGetUnansweredInferenceRunRequest) Reset()         { *m = QueryGetUnansweredInferenceRunRequest{} }
func (m *QueryGetUnansweredInferenceRunRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUnansweredInferenceRunRequest) ProtoMessage()    {}
func (*QueryGetUnansweredInferenceRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{6}
}
func (m *QueryGetUnansweredInferenceRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUnansweredInferenceRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUnansweredInferenceRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUnansweredInferenceRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUnansweredInferenceRunRequest.Merge(m, src)
}
func (m *QueryGetUnansweredInferenceRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUnansweredInferenceRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUnansweredInferenceRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUnansweredInferenceRunRequest proto.InternalMessageInfo

func (m *QueryGetUnansweredInferenceRunRequest) GetModelId() uint64 {
	if m != nil {
		return m.ModelId
	}
	return 0
}

type QueryGetUnansweredInferenceRunResponse struct {
	Inference *Inferencerun `protobuf:"bytes,1,opt,name=inference,proto3" json:"inference,omitempty"`
}

func (m *QueryGetUnansweredInferenceRunResponse) Reset() {
	*m = QueryGetUnansweredInferenceRunResponse{}
}
func (m *QueryGetUnansweredInferenceRunResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUnansweredInferenceRunResponse) ProtoMessage()    {}
func (*QueryGetUnansweredInferenceRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_899a07530dd29761, []int{7}
}
func (m *QueryGetUnansweredInferenceRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUnansweredInferenceRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUnansweredInferenceRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUnansweredInferenceRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUnansweredInferenceRunResponse.Merge(m, src)
}
func (m *QueryGetUnansweredInferenceRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUnansweredInferenceRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUnansweredInferenceRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUnansweredInferenceRunResponse proto.InternalMessageInfo

func (m *QueryGetUnansweredInferenceRunResponse) GetInference() *Inferencerun {
	if m != nil {
		return m.Inference
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmosllm.inference.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmosllm.inference.QueryParamsResponse")
	proto.RegisterType((*QueryGetInferenceRunRequest)(nil), "cosmosllm.inference.QueryGetInferenceRunRequest")
	proto.RegisterType((*QueryGetInferenceRunResponse)(nil), "cosmosllm.inference.QueryGetInferenceRunResponse")
	proto.RegisterType((*QueryGetPoolSizeRequest)(nil), "cosmosllm.inference.QueryGetPoolSizeRequest")
	proto.RegisterType((*QueryGetPoolSizeResponse)(nil), "cosmosllm.inference.QueryGetPoolSizeResponse")
	proto.RegisterType((*QueryGetUnansweredInferenceRunRequest)(nil), "cosmosllm.inference.QueryGetUnansweredInferenceRunRequest")
	proto.RegisterType((*QueryGetUnansweredInferenceRunResponse)(nil), "cosmosllm.inference.QueryGetUnansweredInferenceRunResponse")
}

func init() { proto.RegisterFile("cosmosllm/inference/query.proto", fileDescriptor_899a07530dd29761) }

var fileDescriptor_899a07530dd29761 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0xad, 0xa7, 0xad, 0x68, 0x9e, 0x04, 0xc2, 0x9b, 0x44, 0x97, 0x55, 0xd9, 0x08, 0x6c, 0x4c,
	0x63, 0x8d, 0xe9, 0x40, 0x1c, 0x00, 0x0d, 0x31, 0x21, 0xa1, 0xde, 0x46, 0xd0, 0x2e, 0x5c, 0x2a,
	0x77, 0x31, 0x91, 0xa5, 0xc4, 0xce, 0xe2, 0x04, 0xd8, 0xd0, 0x0e, 0xf0, 0x0b, 0x90, 0x38, 0xf0,
	0x17, 0x38, 0x70, 0x80, 0x7f, 0xb1, 0xe3, 0x24, 0x2e, 0x88, 0x03, 0x42, 0x2d, 0x12, 0x7f, 0x03,
	0xd5, 0x71, 0x42, 0xe9, 0xdc, 0x0e, 0x10, 0x97, 0xea, 0xb3, 0xfd, 0xbe, 0xf7, 0xde, 0x67, 0xbf,
	0x06, 0x2e, 0xee, 0x0a, 0x19, 0x09, 0x19, 0x86, 0x11, 0x66, 0xfc, 0x09, 0x4d, 0x28, 0xdf, 0xa5,
	0x78, 0x2f, 0xa3, 0xc9, 0xbe, 0x1b, 0x27, 0x22, 0x15, 0x68, 0xb6, 0x04, 0xb8, 0x25, 0xc0, 0x3a,
	0x4f, 0x22, 0xc6, 0x05, 0x56, 0xbf, 0x39, 0xce, 0x9a, 0x0b, 0x44, 0x20, 0x54, 0x89, 0xfb, 0x95,
	0xde, 0xad, 0x07, 0x42, 0x04, 0x21, 0xc5, 0x24, 0x66, 0x98, 0x70, 0x2e, 0x52, 0x92, 0x32, 0xc1,
	0xa5, 0x3e, 0x5d, 0xcb, 0xb9, 0x71, 0x87, 0x48, 0x2d, 0x8a, 0x9f, 0x36, 0x3b, 0x34, 0x25, 0x4d,
	0x1c, 0x93, 0x80, 0x71, 0x05, 0xd6, 0xd8, 0x25, 0x93, 0xd1, 0x98, 0x24, 0x24, 0x2a, 0xd8, 0x56,
	0x4c, 0x88, 0xb2, 0x4a, 0x32, 0xcd, 0xe4, 0xcc, 0x41, 0xf4, 0xb0, 0xaf, 0xb5, 0xad, 0x9a, 0x3d,
	0xba, 0x97, 0x51, 0x99, 0x3a, 0x3b, 0x70, 0xf6, 0xb7, 0x5d, 0x19, 0x0b, 0x2e, 0x29, 0xda, 0x84,
	0xd5, 0x5c, 0xa4, 0x06, 0x96, 0xc0, 0xea, 0xcc, 0xc6, 0x82, 0x6b, 0xb8, 0x0f, 0x37, 0x6f, 0xda,
	0x9a, 0x3e, 0xfa, 0xba, 0x58, 0x79, 0xf7, 0xe3, 0xc3, 0x1a, 0xf0, 0x74, 0x97, 0xd3, 0x80, 0x0b,
	0x8a, 0xf6, 0x01, 0x4d, 0x5b, 0x05, 0xdc, 0xcb, 0xb8, 0x56, 0x45, 0x67, 0xe1, 0x04, 0xf3, 0x15,
	0xf5, 0xa4, 0x37, 0xc1, 0x7c, 0xa7, 0x0d, 0xeb, 0x66, 0xb8, 0xb6, 0x73, 0x17, 0x4e, 0x97, 0xaa,
	0xda, 0xd1, 0x45, 0xa3, 0xa3, 0xd6, 0xc0, 0xdc, 0xde, 0xaf, 0x1e, 0x67, 0x1e, 0x5e, 0x28, 0x04,
	0xb6, 0x85, 0x08, 0x1f, 0xb1, 0x03, 0x5a, 0xdc, 0x80, 0x0b, 0x6b, 0x27, 0x8f, 0xb4, 0x2e, 0x82,
	0x93, 0x92, 0x1d, 0x50, 0xed, 0x54, 0xd5, 0xce, 0x3d, 0xb8, 0x5c, 0xe0, 0x77, 0x38, 0xe1, 0xf2,
	0x19, 0x4d, 0xa8, 0x6f, 0x1a, 0xb2, 0x06, 0xcf, 0x44, 0xc2, 0xa7, 0x61, 0xab, 0x98, 0xb4, 0x58,
	0x3a, 0x0c, 0xae, 0x9c, 0x46, 0xf1, 0x9f, 0x06, 0xdf, 0xf8, 0x38, 0x05, 0xa7, 0x94, 0x16, 0x7a,
	0x09, 0x60, 0x35, 0x7f, 0x30, 0x74, 0xc5, 0x48, 0x71, 0x32, 0x1d, 0xd6, 0xea, 0xe9, 0xc0, 0xdc,
	0xa8, 0x73, 0xf9, 0xd5, 0xa7, 0xef, 0x6f, 0x26, 0x6c, 0x54, 0xc7, 0x79, 0x47, 0xc3, 0x94, 0x58,
	0xf4, 0x1e, 0xc0, 0x73, 0x43, 0x6f, 0x8c, 0xae, 0x8d, 0xd6, 0x30, 0xa7, 0xc7, 0x6a, 0xfe, 0x45,
	0x87, 0xb6, 0x77, 0x43, 0xd9, 0x73, 0xd1, 0xba, 0xd9, 0x5e, 0x40, 0xd3, 0x76, 0xb9, 0x6a, 0x27,
	0x19, 0xc7, 0x2f, 0x98, 0x7f, 0x88, 0xde, 0x02, 0x38, 0x33, 0x10, 0x0b, 0xb4, 0x3e, 0x56, 0x78,
	0x28, 0x58, 0x56, 0xe3, 0x0f, 0xd1, 0xda, 0xe2, 0x55, 0x65, 0x71, 0x19, 0x5d, 0x1a, 0x6d, 0x31,
	0x16, 0x22, 0x6c, 0xf7, 0x43, 0x88, 0xbe, 0x00, 0x38, 0x3f, 0x32, 0x3d, 0xe8, 0xd6, 0x58, 0xe5,
	0xb1, 0xa9, 0xb5, 0x6e, 0xff, 0x53, 0xaf, 0x9e, 0xe1, 0xbe, 0x9a, 0x61, 0x13, 0xdd, 0x19, 0x3d,
	0x43, 0x56, 0x32, 0x0c, 0xdf, 0xb8, 0xfe, 0x77, 0x1c, 0x6e, 0xdd, 0x3c, 0xea, 0xda, 0xe0, 0xb8,
	0x6b, 0x83, 0x6f, 0x5d, 0x1b, 0xbc, 0xee, 0xd9, 0x95, 0xe3, 0x9e, 0x5d, 0xf9, 0xdc, 0xb3, 0x2b,
	0x8f, 0xeb, 0x03, 0xb4, 0xcf, 0x07, 0x88, 0xd3, 0xfd, 0x98, 0xca, 0x4e, 0x55, 0x7d, 0xe8, 0xae,
	0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x15, 0x4b, 0x08, 0x08, 0xdd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetInferenceRun items.
	GetInferenceRun(ctx context.Context, in *QueryGetInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetInferenceRunResponse, error)
	// Queries a list of GetPoolSize items.
	GetPoolSize(ctx context.Context, in *QueryGetPoolSizeRequest, opts ...grpc.CallOption) (*QueryGetPoolSizeResponse, error)
	// Queries a list of GetUnansweredInferenceRun items.
	GetUnansweredInferenceRun(ctx context.Context, in *QueryGetUnansweredInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetUnansweredInferenceRunResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmosllm.inference.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetInferenceRun(ctx context.Context, in *QueryGetInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetInferenceRunResponse, error) {
	out := new(QueryGetInferenceRunResponse)
	err := c.cc.Invoke(ctx, "/cosmosllm.inference.Query/GetInferenceRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPoolSize(ctx context.Context, in *QueryGetPoolSizeRequest, opts ...grpc.CallOption) (*QueryGetPoolSizeResponse, error) {
	out := new(QueryGetPoolSizeResponse)
	err := c.cc.Invoke(ctx, "/cosmosllm.inference.Query/GetPoolSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetUnansweredInferenceRun(ctx context.Context, in *QueryGetUnansweredInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetUnansweredInferenceRunResponse, error) {
	out := new(QueryGetUnansweredInferenceRunResponse)
	err := c.cc.Invoke(ctx, "/cosmosllm.inference.Query/GetUnansweredInferenceRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetInferenceRun items.
	GetInferenceRun(context.Context, *QueryGetInferenceRunRequest) (*QueryGetInferenceRunResponse, error)
	// Queries a list of GetPoolSize items.
	GetPoolSize(context.Context, *QueryGetPoolSizeRequest) (*QueryGetPoolSizeResponse, error)
	// Queries a list of GetUnansweredInferenceRun items.
	GetUnansweredInferenceRun(context.Context, *QueryGetUnansweredInferenceRunRequest) (*QueryGetUnansweredInferenceRunResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetInferenceRun(ctx context.Context, req *QueryGetInferenceRunRequest) (*QueryGetInferenceRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInferenceRun not implemented")
}
func (*UnimplementedQueryServer) GetPoolSize(ctx context.Context, req *QueryGetPoolSizeRequest) (*QueryGetPoolSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolSize not implemented")
}
func (*UnimplementedQueryServer) GetUnansweredInferenceRun(ctx context.Context, req *QueryGetUnansweredInferenceRunRequest) (*QueryGetUnansweredInferenceRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnansweredInferenceRun not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosllm.inference.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetInferenceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetInferenceRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetInferenceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosllm.inference.Query/GetInferenceRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetInferenceRun(ctx, req.(*QueryGetInferenceRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPoolSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPoolSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPoolSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosllm.inference.Query/GetPoolSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPoolSize(ctx, req.(*QueryGetPoolSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetUnansweredInferenceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUnansweredInferenceRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetUnansweredInferenceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosllm.inference.Query/GetUnansweredInferenceRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetUnansweredInferenceRun(ctx, req.(*QueryGetUnansweredInferenceRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmosllm.inference.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetInferenceRun",
			Handler:    _Query_GetInferenceRun_Handler,
		},
		{
			MethodName: "GetPoolSize",
			Handler:    _Query_GetPoolSize_Handler,
		},
		{
			MethodName: "GetUnansweredInferenceRun",
			Handler:    _Query_GetUnansweredInferenceRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosllm/inference/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetInferenceRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInferenceRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInferenceRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetInferenceRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInferenceRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInferenceRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Inference != nil {
		{
			size, err := m.Inference.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPoolSizeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPoolSizeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPoolSizeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPoolSizeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPoolSizeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPoolSizeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Size_ != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUnansweredInferenceRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUnansweredInferenceRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUnansweredInferenceRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ModelId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ModelId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUnansweredInferenceRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUnansweredInferenceRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUnansweredInferenceRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Inference != nil {
		{
			size, err := m.Inference.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetInferenceRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetInferenceRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Inference != nil {
		l = m.Inference.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPoolSizeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPoolSizeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Size_ != 0 {
		n += 1 + sovQuery(uint64(m.Size_))
	}
	return n
}

func (m *QueryGetUnansweredInferenceRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ModelId != 0 {
		n += 1 + sovQuery(uint64(m.ModelId))
	}
	return n
}

func (m *QueryGetUnansweredInferenceRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Inference != nil {
		l = m.Inference.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetInferenceRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInferenceRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInferenceRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetInferenceRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInferenceRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInferenceRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inference", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Inference == nil {
				m.Inference = &Inferencerun{}
			}
			if err := m.Inference.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPoolSizeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPoolSizeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPoolSizeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPoolSizeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPoolSizeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPoolSizeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUnansweredInferenceRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUnansweredInferenceRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUnansweredInferenceRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			m.ModelId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModelId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUnansweredInferenceRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUnansweredInferenceRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUnansweredInferenceRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inference", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Inference == nil {
				m.Inference = &Inferencerun{}
			}
			if err := m.Inference.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
