// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosllm/inference/staked_gpu_node.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StakedGpuNode struct {
	Owner        string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Stake        uint64 `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	Denom        string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	SuccessCount uint64 `protobuf:"varint,4,opt,name=successCount,proto3" json:"successCount,omitempty"`
	FailCount    uint64 `protobuf:"varint,5,opt,name=failCount,proto3" json:"failCount,omitempty"`
	GpuModel     string `protobuf:"bytes,6,opt,name=gpuModel,proto3" json:"gpuModel,omitempty"`
	Memory       uint64 `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Cores        uint64 `protobuf:"varint,8,opt,name=cores,proto3" json:"cores,omitempty"`
}

func (m *StakedGpuNode) Reset()         { *m = StakedGpuNode{} }
func (m *StakedGpuNode) String() string { return proto.CompactTextString(m) }
func (*StakedGpuNode) ProtoMessage()    {}
func (*StakedGpuNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_e70639e418a1ba36, []int{0}
}
func (m *StakedGpuNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakedGpuNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakedGpuNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakedGpuNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakedGpuNode.Merge(m, src)
}
func (m *StakedGpuNode) XXX_Size() int {
	return m.Size()
}
func (m *StakedGpuNode) XXX_DiscardUnknown() {
	xxx_messageInfo_StakedGpuNode.DiscardUnknown(m)
}

var xxx_messageInfo_StakedGpuNode proto.InternalMessageInfo

func (m *StakedGpuNode) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *StakedGpuNode) GetStake() uint64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

func (m *StakedGpuNode) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *StakedGpuNode) GetSuccessCount() uint64 {
	if m != nil {
		return m.SuccessCount
	}
	return 0
}

func (m *StakedGpuNode) GetFailCount() uint64 {
	if m != nil {
		return m.FailCount
	}
	return 0
}

func (m *StakedGpuNode) GetGpuModel() string {
	if m != nil {
		return m.GpuModel
	}
	return ""
}

func (m *StakedGpuNode) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *StakedGpuNode) GetCores() uint64 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func init() {
	proto.RegisterType((*StakedGpuNode)(nil), "cosmosllm.inference.StakedGpuNode")
}

func init() {
	proto.RegisterFile("cosmosllm/inference/staked_gpu_node.proto", fileDescriptor_e70639e418a1ba36)
}

var fileDescriptor_e70639e418a1ba36 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4b, 0x03, 0x31,
	0x18, 0x86, 0x2f, 0xda, 0x9e, 0x6d, 0xd0, 0x25, 0x8a, 0x04, 0x29, 0xa1, 0x74, 0xaa, 0x83, 0xed,
	0x20, 0xf8, 0x03, 0x74, 0x70, 0xd2, 0xa1, 0x6e, 0x2e, 0xa5, 0x26, 0x5f, 0x4b, 0xf1, 0x92, 0x2f,
	0x24, 0x17, 0xb4, 0xff, 0xc2, 0x9f, 0xe5, 0x78, 0xa3, 0x8b, 0x20, 0x77, 0x7f, 0x44, 0x2e, 0x91,
	0x53, 0xc7, 0xe7, 0xe5, 0xf9, 0x3e, 0x5e, 0x5e, 0x7a, 0x2e, 0xd1, 0x6b, 0xf4, 0x45, 0xa1, 0xe7,
	0x5b, 0xb3, 0x06, 0x07, 0x46, 0xc2, 0xdc, 0x97, 0xab, 0x67, 0x50, 0xcb, 0x8d, 0x0d, 0x4b, 0x83,
	0x0a, 0x66, 0xd6, 0x61, 0x89, 0xec, 0xb8, 0x53, 0x67, 0x9d, 0x3a, 0xf9, 0x24, 0xf4, 0xe8, 0x21,
	0xea, 0xb7, 0x36, 0xdc, 0xa3, 0x02, 0x76, 0x42, 0xfb, 0xf8, 0x62, 0xc0, 0x71, 0x32, 0x26, 0xd3,
	0xe1, 0x22, 0x41, 0x9b, 0xc6, 0xaf, 0x7c, 0x6f, 0x4c, 0xa6, 0xbd, 0x45, 0x82, 0x36, 0x55, 0x60,
	0x50, 0xf3, 0xfd, 0xe4, 0x46, 0x60, 0x13, 0x7a, 0xe8, 0x83, 0x94, 0xe0, 0xfd, 0x0d, 0x06, 0x53,
	0xf2, 0x5e, 0x3c, 0xf9, 0x97, 0xb1, 0x11, 0x1d, 0xae, 0x57, 0xdb, 0x22, 0x09, 0xfd, 0x28, 0xfc,
	0x06, 0xec, 0x8c, 0x0e, 0x36, 0x36, 0xdc, 0xa1, 0x82, 0x82, 0xe7, 0xf1, 0x75, 0xc7, 0xec, 0x94,
	0xe6, 0x1a, 0x34, 0xba, 0x1d, 0x3f, 0x88, 0x67, 0x3f, 0xd4, 0x76, 0x91, 0xe8, 0xc0, 0xf3, 0x41,
	0x6a, 0x18, 0xe1, 0xfa, 0xea, 0xbd, 0x16, 0xa4, 0xaa, 0x05, 0xf9, 0xaa, 0x05, 0x79, 0x6b, 0x44,
	0x56, 0x35, 0x22, 0xfb, 0x68, 0x44, 0xf6, 0x38, 0x4a, 0x73, 0x5c, 0xb4, 0xd3, 0xbd, 0xfe, 0x19,
	0xaf, 0xdc, 0x59, 0xf0, 0x4f, 0x79, 0xdc, 0xec, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x02,
	0x8d, 0x3b, 0x60, 0x01, 0x00, 0x00,
}

func (m *StakedGpuNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakedGpuNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakedGpuNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cores != 0 {
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(m.Cores))
		i--
		dAtA[i] = 0x40
	}
	if m.Memory != 0 {
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(m.Memory))
		i--
		dAtA[i] = 0x38
	}
	if len(m.GpuModel) > 0 {
		i -= len(m.GpuModel)
		copy(dAtA[i:], m.GpuModel)
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(len(m.GpuModel)))
		i--
		dAtA[i] = 0x32
	}
	if m.FailCount != 0 {
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(m.FailCount))
		i--
		dAtA[i] = 0x28
	}
	if m.SuccessCount != 0 {
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(m.SuccessCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Stake != 0 {
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(m.Stake))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintStakedGpuNode(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStakedGpuNode(dAtA []byte, offset int, v uint64) int {
	offset -= sovStakedGpuNode(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StakedGpuNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovStakedGpuNode(uint64(l))
	}
	if m.Stake != 0 {
		n += 1 + sovStakedGpuNode(uint64(m.Stake))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovStakedGpuNode(uint64(l))
	}
	if m.SuccessCount != 0 {
		n += 1 + sovStakedGpuNode(uint64(m.SuccessCount))
	}
	if m.FailCount != 0 {
		n += 1 + sovStakedGpuNode(uint64(m.FailCount))
	}
	l = len(m.GpuModel)
	if l > 0 {
		n += 1 + l + sovStakedGpuNode(uint64(l))
	}
	if m.Memory != 0 {
		n += 1 + sovStakedGpuNode(uint64(m.Memory))
	}
	if m.Cores != 0 {
		n += 1 + sovStakedGpuNode(uint64(m.Cores))
	}
	return n
}

func sovStakedGpuNode(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStakedGpuNode(x uint64) (n int) {
	return sovStakedGpuNode(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StakedGpuNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakedGpuNode
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakedGpuNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakedGpuNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakedGpuNode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakedGpuNode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stake", wireType)
			}
			m.Stake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakedGpuNode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakedGpuNode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuccessCount", wireType)
			}
			m.SuccessCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SuccessCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailCount", wireType)
			}
			m.FailCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FailCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GpuModel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakedGpuNode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakedGpuNode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GpuModel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			m.Memory = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Memory |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cores", wireType)
			}
			m.Cores = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cores |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStakedGpuNode(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakedGpuNode
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStakedGpuNode(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStakedGpuNode
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakedGpuNode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStakedGpuNode
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStakedGpuNode
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStakedGpuNode
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStakedGpuNode        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStakedGpuNode          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStakedGpuNode = fmt.Errorf("proto: unexpected end of group")
)
