// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package inference

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Gpunode          protoreflect.MessageDescriptor
	fd_Gpunode_gpuModel protoreflect.FieldDescriptor
	fd_Gpunode_memory   protoreflect.FieldDescriptor
	fd_Gpunode_cores    protoreflect.FieldDescriptor
)

func init() {
	file_cosmosllm_inference_gpunode_proto_init()
	md_Gpunode = File_cosmosllm_inference_gpunode_proto.Messages().ByName("Gpunode")
	fd_Gpunode_gpuModel = md_Gpunode.Fields().ByName("gpuModel")
	fd_Gpunode_memory = md_Gpunode.Fields().ByName("memory")
	fd_Gpunode_cores = md_Gpunode.Fields().ByName("cores")
}

var _ protoreflect.Message = (*fastReflection_Gpunode)(nil)

type fastReflection_Gpunode Gpunode

func (x *Gpunode) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Gpunode)(x)
}

func (x *Gpunode) slowProtoReflect() protoreflect.Message {
	mi := &file_cosmosllm_inference_gpunode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Gpunode_messageType fastReflection_Gpunode_messageType
var _ protoreflect.MessageType = fastReflection_Gpunode_messageType{}

type fastReflection_Gpunode_messageType struct{}

func (x fastReflection_Gpunode_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Gpunode)(nil)
}
func (x fastReflection_Gpunode_messageType) New() protoreflect.Message {
	return new(fastReflection_Gpunode)
}
func (x fastReflection_Gpunode_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Gpunode
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Gpunode) Descriptor() protoreflect.MessageDescriptor {
	return md_Gpunode
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Gpunode) Type() protoreflect.MessageType {
	return _fastReflection_Gpunode_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Gpunode) New() protoreflect.Message {
	return new(fastReflection_Gpunode)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Gpunode) Interface() protoreflect.ProtoMessage {
	return (*Gpunode)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Gpunode) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.GpuModel != "" {
		value := protoreflect.ValueOfString(x.GpuModel)
		if !f(fd_Gpunode_gpuModel, value) {
			return
		}
	}
	if x.Memory != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Memory)
		if !f(fd_Gpunode_memory, value) {
			return
		}
	}
	if x.Cores != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Cores)
		if !f(fd_Gpunode_cores, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Gpunode) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "cosmosllm.inference.Gpunode.gpuModel":
		return x.GpuModel != ""
	case "cosmosllm.inference.Gpunode.memory":
		return x.Memory != uint64(0)
	case "cosmosllm.inference.Gpunode.cores":
		return x.Cores != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmosllm.inference.Gpunode"))
		}
		panic(fmt.Errorf("message cosmosllm.inference.Gpunode does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Gpunode) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "cosmosllm.inference.Gpunode.gpuModel":
		x.GpuModel = ""
	case "cosmosllm.inference.Gpunode.memory":
		x.Memory = uint64(0)
	case "cosmosllm.inference.Gpunode.cores":
		x.Cores = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmosllm.inference.Gpunode"))
		}
		panic(fmt.Errorf("message cosmosllm.inference.Gpunode does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Gpunode) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "cosmosllm.inference.Gpunode.gpuModel":
		value := x.GpuModel
		return protoreflect.ValueOfString(value)
	case "cosmosllm.inference.Gpunode.memory":
		value := x.Memory
		return protoreflect.ValueOfUint64(value)
	case "cosmosllm.inference.Gpunode.cores":
		value := x.Cores
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmosllm.inference.Gpunode"))
		}
		panic(fmt.Errorf("message cosmosllm.inference.Gpunode does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Gpunode) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "cosmosllm.inference.Gpunode.gpuModel":
		x.GpuModel = value.Interface().(string)
	case "cosmosllm.inference.Gpunode.memory":
		x.Memory = value.Uint()
	case "cosmosllm.inference.Gpunode.cores":
		x.Cores = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmosllm.inference.Gpunode"))
		}
		panic(fmt.Errorf("message cosmosllm.inference.Gpunode does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Gpunode) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmosllm.inference.Gpunode.gpuModel":
		panic(fmt.Errorf("field gpuModel of message cosmosllm.inference.Gpunode is not mutable"))
	case "cosmosllm.inference.Gpunode.memory":
		panic(fmt.Errorf("field memory of message cosmosllm.inference.Gpunode is not mutable"))
	case "cosmosllm.inference.Gpunode.cores":
		panic(fmt.Errorf("field cores of message cosmosllm.inference.Gpunode is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmosllm.inference.Gpunode"))
		}
		panic(fmt.Errorf("message cosmosllm.inference.Gpunode does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Gpunode) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmosllm.inference.Gpunode.gpuModel":
		return protoreflect.ValueOfString("")
	case "cosmosllm.inference.Gpunode.memory":
		return protoreflect.ValueOfUint64(uint64(0))
	case "cosmosllm.inference.Gpunode.cores":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmosllm.inference.Gpunode"))
		}
		panic(fmt.Errorf("message cosmosllm.inference.Gpunode does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Gpunode) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in cosmosllm.inference.Gpunode", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Gpunode) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Gpunode) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Gpunode) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Gpunode) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Gpunode)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.GpuModel)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Memory != 0 {
			n += 1 + runtime.Sov(uint64(x.Memory))
		}
		if x.Cores != 0 {
			n += 1 + runtime.Sov(uint64(x.Cores))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Gpunode)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Cores != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Cores))
			i--
			dAtA[i] = 0x18
		}
		if x.Memory != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Memory))
			i--
			dAtA[i] = 0x10
		}
		if len(x.GpuModel) > 0 {
			i -= len(x.GpuModel)
			copy(dAtA[i:], x.GpuModel)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.GpuModel)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Gpunode)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Gpunode: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Gpunode: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GpuModel", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.GpuModel = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
				}
				x.Memory = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Memory |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Cores", wireType)
				}
				x.Cores = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Cores |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: cosmosllm/inference/gpunode.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gpunode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GpuModel string `protobuf:"bytes,1,opt,name=gpuModel,proto3" json:"gpuModel,omitempty"`
	Memory   uint64 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Cores    uint64 `protobuf:"varint,3,opt,name=cores,proto3" json:"cores,omitempty"`
}

func (x *Gpunode) Reset() {
	*x = Gpunode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmosllm_inference_gpunode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gpunode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gpunode) ProtoMessage() {}

// Deprecated: Use Gpunode.ProtoReflect.Descriptor instead.
func (*Gpunode) Descriptor() ([]byte, []int) {
	return file_cosmosllm_inference_gpunode_proto_rawDescGZIP(), []int{0}
}

func (x *Gpunode) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *Gpunode) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Gpunode) GetCores() uint64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

var File_cosmosllm_inference_gpunode_proto protoreflect.FileDescriptor

var file_cosmosllm_inference_gpunode_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x6c, 0x6c, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x67, 0x70, 0x75, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x6c, 0x6c, 0x6d, 0x2e, 0x69,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x53, 0x0a, 0x07, 0x47, 0x70, 0x75, 0x6e,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0xba, 0x01,
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x6c, 0x6c, 0x6d, 0x2e,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x0c, 0x47, 0x70, 0x75, 0x6e, 0x6f,
	0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x6c, 0x6c, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0xa2,
	0x02, 0x03, 0x43, 0x49, 0x58, 0xaa, 0x02, 0x13, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x6c, 0x6c,
	0x6d, 0x2e, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0xca, 0x02, 0x13, 0x43, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x6c, 0x6c, 0x6d, 0x5c, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0xe2, 0x02, 0x1f, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x6c, 0x6c, 0x6d, 0x5c, 0x49, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x14, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x6c, 0x6c, 0x6d, 0x3a,
	0x3a, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cosmosllm_inference_gpunode_proto_rawDescOnce sync.Once
	file_cosmosllm_inference_gpunode_proto_rawDescData = file_cosmosllm_inference_gpunode_proto_rawDesc
)

func file_cosmosllm_inference_gpunode_proto_rawDescGZIP() []byte {
	file_cosmosllm_inference_gpunode_proto_rawDescOnce.Do(func() {
		file_cosmosllm_inference_gpunode_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmosllm_inference_gpunode_proto_rawDescData)
	})
	return file_cosmosllm_inference_gpunode_proto_rawDescData
}

var file_cosmosllm_inference_gpunode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cosmosllm_inference_gpunode_proto_goTypes = []interface{}{
	(*Gpunode)(nil), // 0: cosmosllm.inference.Gpunode
}
var file_cosmosllm_inference_gpunode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmosllm_inference_gpunode_proto_init() }
func file_cosmosllm_inference_gpunode_proto_init() {
	if File_cosmosllm_inference_gpunode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosmosllm_inference_gpunode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gpunode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmosllm_inference_gpunode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmosllm_inference_gpunode_proto_goTypes,
		DependencyIndexes: file_cosmosllm_inference_gpunode_proto_depIdxs,
		MessageInfos:      file_cosmosllm_inference_gpunode_proto_msgTypes,
	}.Build()
	File_cosmosllm_inference_gpunode_proto = out.File
	file_cosmosllm_inference_gpunode_proto_rawDesc = nil
	file_cosmosllm_inference_gpunode_proto_goTypes = nil
	file_cosmosllm_inference_gpunode_proto_depIdxs = nil
}
