// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmosllm/inference/query.proto

package inference

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName                    = "/cosmosllm.inference.Query/Params"
	Query_GetInferenceRun_FullMethodName           = "/cosmosllm.inference.Query/GetInferenceRun"
	Query_GetPoolSize_FullMethodName               = "/cosmosllm.inference.Query/GetPoolSize"
	Query_GetUnansweredInferenceRun_FullMethodName = "/cosmosllm.inference.Query/GetUnansweredInferenceRun"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetInferenceRun items.
	GetInferenceRun(ctx context.Context, in *QueryGetInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetInferenceRunResponse, error)
	// Queries a list of GetPoolSize items.
	GetPoolSize(ctx context.Context, in *QueryGetPoolSizeRequest, opts ...grpc.CallOption) (*QueryGetPoolSizeResponse, error)
	// Queries a list of GetUnansweredInferenceRun items.
	GetUnansweredInferenceRun(ctx context.Context, in *QueryGetUnansweredInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetUnansweredInferenceRunResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetInferenceRun(ctx context.Context, in *QueryGetInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetInferenceRunResponse, error) {
	out := new(QueryGetInferenceRunResponse)
	err := c.cc.Invoke(ctx, Query_GetInferenceRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPoolSize(ctx context.Context, in *QueryGetPoolSizeRequest, opts ...grpc.CallOption) (*QueryGetPoolSizeResponse, error) {
	out := new(QueryGetPoolSizeResponse)
	err := c.cc.Invoke(ctx, Query_GetPoolSize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetUnansweredInferenceRun(ctx context.Context, in *QueryGetUnansweredInferenceRunRequest, opts ...grpc.CallOption) (*QueryGetUnansweredInferenceRunResponse, error) {
	out := new(QueryGetUnansweredInferenceRunResponse)
	err := c.cc.Invoke(ctx, Query_GetUnansweredInferenceRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetInferenceRun items.
	GetInferenceRun(context.Context, *QueryGetInferenceRunRequest) (*QueryGetInferenceRunResponse, error)
	// Queries a list of GetPoolSize items.
	GetPoolSize(context.Context, *QueryGetPoolSizeRequest) (*QueryGetPoolSizeResponse, error)
	// Queries a list of GetUnansweredInferenceRun items.
	GetUnansweredInferenceRun(context.Context, *QueryGetUnansweredInferenceRunRequest) (*QueryGetUnansweredInferenceRunResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetInferenceRun(context.Context, *QueryGetInferenceRunRequest) (*QueryGetInferenceRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInferenceRun not implemented")
}
func (UnimplementedQueryServer) GetPoolSize(context.Context, *QueryGetPoolSizeRequest) (*QueryGetPoolSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolSize not implemented")
}
func (UnimplementedQueryServer) GetUnansweredInferenceRun(context.Context, *QueryGetUnansweredInferenceRunRequest) (*QueryGetUnansweredInferenceRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnansweredInferenceRun not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetInferenceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetInferenceRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetInferenceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetInferenceRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetInferenceRun(ctx, req.(*QueryGetInferenceRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPoolSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPoolSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPoolSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetPoolSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPoolSize(ctx, req.(*QueryGetPoolSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetUnansweredInferenceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUnansweredInferenceRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetUnansweredInferenceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetUnansweredInferenceRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetUnansweredInferenceRun(ctx, req.(*QueryGetUnansweredInferenceRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmosllm.inference.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetInferenceRun",
			Handler:    _Query_GetInferenceRun_Handler,
		},
		{
			MethodName: "GetPoolSize",
			Handler:    _Query_GetPoolSize_Handler,
		},
		{
			MethodName: "GetUnansweredInferenceRun",
			Handler:    _Query_GetUnansweredInferenceRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosllm/inference/query.proto",
}
